experiment:
  name: "sklearn_classification_experiment"
  tracking_uri: "sqlite:///metadata/mlflow/mlruns.db"
  artifact_location: "./metadata/mlflow/mlartifacts"

# Set the registry server URI. This property is especially useful if you have a registry
# server that’s different from the tracking server.
model_registry:
  # registry_uri: "sqlite:////tmp/registry.db"
  # FIXME::REQUIRED: Specifies the name of the Registered Model to use when registering a trained
  #                 model to the MLflow Model Registry.
  model_name: "complaints_classifier"

# Override the default train / validation / test dataset split ratios
SPLIT_RATIOS: [0.7, 0.15, 0.15]

INGEST_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-classification-template#ingest-step
  using: parquet
  location: "./data/complaints.parquet"

INGEST_SCORING_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-classification-template#batch-scoring
  using: parquet
  location: "./data/complaints.parquet"

PREDICT_OUTPUT_CONFIG:
  # For different options please read: https://github.com/mlflow/recipes-classification-template#predict-step
  using: parquet
  location: "./data/test_prediction_out.parquet"
